# Site settings
title: P3
author:
  name: Umesh Kumar
  email: umesh.kumar@icts.res.in
description: "Python, Physics, PhD."

# Build settings
remote_theme: jekyll/minima

# Navigation tabs
header_pages:
  - courses.md # PhD
  - projects.md # Physics
  - python.md
